### PR TITLE
Syntax highlighted code blocks

### PR DESCRIPTION
**Pull request by drewsberry**
I should really be doing my report...

### CODE REVIEW

**Comment by hmac** [comment]
Me too

**Comment by hmac** [comment]
This should really be merged into development; you can see some of the changes have already been made there. We're trying to leave master alone and just periodically merge dev into it.

**Comment by hmac** [comment]
testing

**Comment by Ap0c** [comment]
Testing what?

**Comment by hmac** [comment]
Webhooks. Picked the first repo I could see.

**Pull request closed without merging**
